# render.yaml
services:
  - type: web
    name: energy-meter-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: "cd backend && npm install" 
    startCommand: "node server.js"
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: persistent_disk
      mountPath: /data
      sizeGB: 1
